Repository tdecker91/Card3D, pull requests merged in 2025-08, with the labels that each got.

#16 Allow adding and removing card collections to `DragController` after it is ready.
  addons/card_3d/scripts/drag_controller.gd
Labels: enhancement

#17 update linter rules
  .gdlintrc
  .github/workflows/godot-ci.yml
Labels: pipeline

#19 fix solitaire example
  example_solitaire/scenes/solitaire.gd
Labels: bug
